# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.2.5
_src_path: gh:algorandfoundation/algokit-python-template
author_email: skillfullmallam@gmail.com
author_name: lafiagi
contract_name: dao
deployment_language: python
preset_name: production
project_name: wakanda

